# Generated by Django 5.2.8 on 2026-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_trainer_picturetrainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
